package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import com.openclassrooms.magicgithub.repository.UserRepository;

import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        //La méthode getUsers() de FakeApiService doit renvoyer une liste d'utilisateurs.
        // Nous pouvons simplement renvoyer la liste users de la classe FakeApiService
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        //La méthode generateRandomUser() doit ajouter un utilisateur aléatoire de FAKE_USERS_RANDOM à la liste users
        //de FakeApiService. Nous pouvons utiliser la méthode generateRandomUser() de la classe UserRepository pour générer
        //un utilisateur aléatoire et l'ajouter à la liste users

        UserRepository userRepository = new UserRepository(this);
        userRepository.generateRandomUser();
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        //La méthode deleteUser(User user) doit supprimer un utilisateur de la liste users de FakeApiService.
        //Nous pouvons utiliser la méthode remove() pour supprimer l'utilisateur de la liste

        users.remove(user);
    }
}
